name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Stop existing service
            sudo systemctl stop solana-bot || true

            # Navigate to bot directory
            cd /home/ec2-user/solana-bot

            # Pull latest changes
            git pull

            # Build bot
            go build -o bot

            # Start service
            sudo systemctl start solana-bot
